config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }

  resources :users, only: %i[index destroy edit update]

  resources :admins, shallow: true do
    resources :subjects, except: :show
  end

  resources :exams
  resources :schedules, except: [:show, :edit]
  resources :results, only: [:index, :show, :create]
  resources :mcqs, only: :destroy
  resources :blanks, only: :destroy
  resources :attempts, only: :show
  resource :dashboard, only: [:show, :new]

  root 'dashboards#show'

  get '*all', to: 'dashboards#new', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  default_scope { order(:created_at) }

  belongs_to :teacher
  belongs_to :exam
  has_many :results, dependent: :destroy

  validates :teacher_id, :exam_id, :start_time, :end_time, presence: true
  validate :start_and_end_time

  enum status: {
    pending: 0,
    approved: 10,
    rejected: 20
  }

  scope :by_teacher, ->(user_id) { where('teacher_id = ?', user_id) }
  scope :active_exams, -> { where('end_time > ? AND status = ?', DateTime.now, 10) }

  private

  def start_and_end_time
    current_time = DateTime.now

    if end_time < current_time
      errors.add(:end_time, 'end time can not be in past')
    elsif start_time > end_time
      errors.add(:end_time, 'end time can\'t be before start time')
    end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  include Setter::ScheduleSetter

  before_action :set_schedule, only: %i[destroy update]
  before_action :set_permission, only: :destroy

  def index
    @schedules = policy_scope(Schedule)
    authorize @schedules
  end

  def new
    @schedule = Schedule.new
    authorize @schedule
  end

  def create
    @schedule = Schedule.new(schedule_params)
    authorize @schedule, :new?

    if @schedule.save
      redirect_to schedules_path, notice: 'Exam Scheduled (Approval Pending)'
    else
      render :new
    end
  end

  def update
    authorize @schedule
    if @schedule.update(schedule_params)
      redirect_to schedules_path, notice: 'Schedule Updated'
    else
      redirect_to schedules_path, alert: 'Could not approve Schedule'
    end
  end

  def destroy
    if @schedule.destroy
      redirect_to schedules_path, notice: 'Schedule Removed'
    else
      redirect_to schedules_path, alert: 'Coul not remove Schedule'
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(Schedule.attribute_names.map(&:to_sym))
  end

  def set_permission
    authorize @schedule
  end
end

app/helpers/schedule_helper.rb
# frozen_string_literal: true

module ScheduleHelper
  def convert_to_local_time(time)
    time.change(offset: '+0500')
  end

  def exams_list
    Exam.by_teacher(current_user.id).where(status: :approved).map { |exam| [exam.title, exam.id] }
  end

  def exam_time_passed_status(schedule)
    if DateTime.now > schedule.end_time
      'Conducted'
    elsif DateTime.now < schedule.start_time
      'Scheduled'
    else
      'Taking Place'
    end
  end

  def no_result(schedule)
    !Result.find_by(student_id: current_user.id, schedule_id: schedule.id)
  end

  def check_available_exams
    Exam.find_by(teacher_id: current_user.id)
  end
end

app/views/schedules/index.html.erb
<% if current_user.Teacher? && check_available_exams %>
  <%= link_to 'Create Schedule', new_schedule_path, class: 'btn btn-primary m2' %>
<% end %>
<h1>Exam Schedules</h1>

<% unless @schedules.blank? %>
  <table>
    <tr>
      <th> Exam </th>
      <th> Subject </th>
      <th> Start Time </th>
      <th> End Time </th>
      <% unless current_user.Student? %>
        <th> Approval </th>
      <% end %>
      <th> Status </th>
      <th> Action </th>
    </tr>

    <% @schedules.each do |schedule| %>
      <tr>
        <td> <p> <%= schedule.exam.title[0, 15] %> </p> </td>
        <td> <p> <%= schedule.exam.subject.name %> </p> </td>
        <td> <p> <%= convert_to_local_time(schedule.start_time) %> </p> </td>
        <td> <p> <%= convert_to_local_time(schedule.end_time) %> </p> </td>
        <% unless current_user.Student? %>
          <td>
            <% if current_user.Admin? && schedule.status == 'pending' %>
              <%= link_to 'Approve', schedule_path(schedule, schedule: {status: :approved}), method: :patch, class: 'btn btn-success m-1' %>
              <%= link_to 'Reject', schedule_path(schedule, schedule: {status: :rejected}), method: :patch, class: 'btn btn-secondary m-1' %>
            <% elsif current_user.Admin? && schedule.status == 'approved' && DateTime.now < schedule.start_time %>
              <%= link_to 'Cancel', schedule_path(schedule, schedule: {status: :rejected}), method: :patch, class: 'btn btn-secondary m-1' %>
            <% else %>
              <p> <%= schedule.status %> </p>
            <% end %>
          </td>
        <% end %>
        <td>
          <p> <%= exam_time_passed_status(schedule) %> </p>
        </td>
        <% unless current_user.Student? %>
          <td>
            <p> <%= link_to 'Delete', schedule_path(schedule), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %> </p>
          </td>
        <% end %>

        <% if current_user.Student? %>
          <% if DateTime.now > schedule.start_time && DateTime.now < schedule.end_time && no_result(schedule) %>
            <td> <p> <%= link_to 'Attempt', attempt_path(schedule), class: 'btn btn-primary' %> </p> </td>
          <% elsif DateTime.now > schedule.end_time %>
            <td> <p> <%= link_to 'View', exam_path(schedule.exam_id), class: 'btn btn-primary' %> </p> </td>
          <% else %>
            <td> <p> Attempted </p> </td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

<% else %>
  <p> No schedules made </p>
<% end %>

app/views/schedules/new.html.erb
<h1>Create Exam Schedule</h1>

<% if @schedule.errors.any? %>
  <% @schedule.errors.full_messages.each do |error| %>
    <p class='alert alert-danger'> <%= error %> </p>
  <% end %>
<% end %>

<%= form_with model: @schedule, local: true do |f| %>
  <%= f.hidden_field :teacher_id, value: current_user.id %>

  <%= f.label :exam %> <br>
  <%= f.select :exam_id, exams_list %> <br>

  <%= f.label :start_time %> <br>
  <%= f.datetime_select :start_time %> <br>

  <%= f.label :end_time %> <br>
  <%= f.datetime_select :end_time %> <br>

  <br>
  <%= f.submit %>
<% end %>