config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }

  resources :users, only: %i[index destroy edit update]

  resources :admins, shallow: true do
    resources :subjects, except: :show
  end

  resources :exams
  resources :schedules, except: [:show, :edit]
  resources :results, only: [:index, :show, :create]
  resources :mcqs, only: :destroy
  resources :blanks, only: :destroy
  resources :attempts, only: :show
  resource :dashboard, only: [:show, :new]

  root 'dashboards#show'

  get '*all', to: 'dashboards#new', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  default_scope { order(:created_at) }

  belongs_to :admin
  belongs_to :teacher
  has_many :exams, dependent: :destroy

  validates :admin_id, :teacher_id, presence: true
  validates :name, presence: true,
                   length: { minimum: 3 }
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action :set_subject, except: %i[index new create]

  include Setter::SubjectSetter

  def index
    @subjects = Subject.all.includes(:teacher, :admin).order(:created_at)
    authorize @subjects
  end

  def show
    authorize @subject, :index?
  end

  def new
    @subject = Subject.new
    authorize @teachers, :new?, policy_class: SubjectPolicy
  end

  def create
    @subject = Subject.new(subject_params)
    authorize @subject, :index?

    if @subject.save
      redirect_to admin_subjects_path(current_user), notice: 'Subject Added'
    else
      render :new
    end
  end

  def edit
    authorize @subject, :index?
  end

  def update
    authorize @subject, :index?

    if @subject.update(subject_params)
      redirect_to admin_subjects_path(current_user), notice: 'Subject updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @subject, :index?

    if @subject.destroy
      redirect_to admin_subjects_path(current_user), notice: 'Subject deleted'
    else
      redirect_to admin_subjects_path(current_user), alert: 'Error! could not delete subject'
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:admin_id, :teacher_id, :name)
  end
end

app/helpers/subject_helper.rb
# frozen_string_literal: true

module SubjectHelper
  def set_teachers
    Teacher.all.map { |teacher| [teacher.name, teacher.id] }
  end
end

app/views/subjects/edit.html.erb
<h1>Edit Subject</h1>

<% if @subject.errors.any? %>
  <% @subject.errors.full_messages.each do |error| %>
    <p class='alert alert-danger'> <%= error %> </p>
  <% end %>
<% end %>

<%= form_with model: @subject, local: true do |f| %>
  <%= f.hidden_field :admin_id, value: current_user.id %> <br>
  <%= f.label :name %> <br>
  <%= f.text_field :name %> <br>
  <%= f.label :teacher %> <br>
  <%= f.select :teacher_id, set_teachers %> <br>

  <br>
  <%= f.submit %>
<% end %>

app/views/subjects/index.html.erb
<%= link_to 'Create Subject', new_admin_subject_path, class: 'btn btn-primary m-2' %>
<h1>Subjects</h1>

<% unless @subjects.blank? %>
  <table>
    <tr>
      <th> Id </th>
      <th> Name </th>
      <th> Teacher </th>
      <th> Admin </th>
      <th> Action </th>
      <th> Action </th>
    </tr>

    <% @subjects.each do |subject| %>
      <tr>
        <td> <p> <%= subject.id %> </p> </td>
        <td> <p> <%= subject.name %> </p> </td>
        <td> <p> <%= subject.teacher.name %> </p> </td>
        <td> <p> <%= subject.admin.name %> </p> </td>
        <td> <p> <%= link_to 'Edit', edit_subject_path(subject), class: 'btn btn-secondary' %> </p> </td>
        <td> <p> <%= link_to 'Delete', subject_path(subject), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %> </p> </td>
      </tr>
    <% end %>
  </table>

<% else %>
  <p> No subjects registered </p>
<% end %>

app/views/subjects/new.html.erb
<h1>Add Subject</h1>

<% if @subject.errors.any? %>
  <% @subject.errors.full_messages.each do |error| %>
    <p class='alert alert-danger'> <%= error %> </p>
  <% end %>
<% end %>

<%= form_with model: [current_user, @subject], local: true do |f| %>
  <%= f.hidden_field :admin_id, value: current_user.id %> <br>
  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %> <br>
  <%= f.label :teacher %> <br>
  <%= f.select :teacher_id, set_teachers, required: true %> <br>

  <br>
  <%= f.submit %>
<% end %>