config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }

  resources :users, only: %i[index destroy edit update]

  resources :admins, shallow: true do
    resources :subjects, except: :show
  end

  resources :exams
  resources :schedules, except: [:show, :edit]
  resources :results, only: [:index, :show, :create]
  resources :mcqs, only: :destroy
  resources :blanks, only: :destroy
  resources :attempts, only: :show
  resource :dashboard, only: [:show, :new]

  root 'dashboards#show'

  get '*all', to: 'dashboards#new', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/exam.rb
# frozen_string_literal: true

class Exam < ApplicationRecord
  default_scope { reorder(created_at: :desc) }

  before_save :calculate_total_marks

  belongs_to :teacher
  belongs_to :subject
  has_many :schedules, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :mcqs, dependent: :destroy
  has_many :blanks, dependent: :destroy
  accepts_nested_attributes_for :mcqs, allow_destroy: true
  accepts_nested_attributes_for :blanks, allow_destroy: true

  validates :title, presence: true, length: { minimum:3 }
  validates :subject_id, presence: true
  validate :empty_exam

  enum status: {
    uncertain: 0,
    rejected: 1,
    approved: 2
  }

  scope :by_teacher, ->(user_id) { where('teacher_id = ?', user_id) }

  private

  def calculate_total_marks
    self.marks = 0

    mcqs.map { |mcq| self.marks += mcq.marks }
    blanks.map { |blank| self.marks += blank.marks }
  end

  def empty_exam
    return unless mcqs.blank? && blanks.blank?

    errors.add(:base, 'An exam needs to have at least one question')
  end
end

app/controllers/exams_controller.rb
# frozen_string_literal: true

class ExamsController < ApplicationController
  include Setter::ExamSetter

  before_action :set_exam, except: %i[index new create]

  def index
    @exams = policy_scope(Exam)
    authorize @exams
  end

  def show
    authorize @exam
  end

  def new
    @previous_exam = Exam.find_by(teacher_id: current_user.id, status: :uncertain) || 'empty'
    @exam = Exam.new
    authorize @previous_exam, :new?, policy_class: ExamPolicy
    @exam.mcqs.build
    @exam.blanks.build
  end

  def create
    @exam = Exam.new(exam_params)
    @subject = @exam.subject
    authorize @subject, policy_class: ExamPolicy

    if @exam.save
      redirect_to exams_path, notice: 'Exam Created (Approval Pending)'
    else
      render :new
    end
  end

  def edit
    authorize @exam

    @schedule = Schedule.find_by(exam_id: @exam)
    return unless @schedule.present? && @schedule.end_time > DateTime.now

    redirect_to exams_path, alert: 'Can not edit scheduled exam'
  end

  def update
    authorize @exam

    if @exam.update(exam_params)
      redirect_to exams_path, notice: 'Exam updated'
    else
      redirect_to exams_path, alert: 'Error! could not update'
    end
  end

  def destroy
    authorize @exam

    if @exam.destroy
      redirect_to exams_path, notice: 'Exam removed'
    else
      redirect_to exams_path, alert: 'Error! could not remove'
    end
  end

  private

  def exam_params
    params.require(:exam).permit(:teacher_id, :subject_id, :title, :status,
                                 mcqs_attributes: Mcq.attribute_names.map(&:to_sym).push(:_destroy),
                                 blanks_attributes: Blank.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/helpers/exam_helper.rb
# frozen_string_literal: true

module ExamHelper
  def subjects_list
    Subject.where(teacher_id: current_user.id).map { |subject| [subject.name, subject.id] }
  end

  def subjects_for_teacher
    Subject.find_by(teacher_id: current_user.id)
  end
end

app/views/exams/_blank.html.erb
<p class='alert alert-secondary p-without-newline m-1'> Question#<%= counter %>. </p>
<p class='p-without-newline'>
  <%= blank&.text_before %>
  <p class='p-without-newline alert alert-secondary'> </p>
  <%= blank&.text_after %>
  [ <%= blank.marks%> ]
</p>

<% unless current_user.Student? %>
  <p class='alert alert-success m-2'> Answer: <%= blank.answer %> </p>
<% end %>

<hr>

app/views/exams/_blank_fields.html.erb
<div class='nested-fields'>
  <div class="card m-2">
    <h5 class="card-header">FITB</h5>
    <div class="card-body">
      <%= f.label :before_part %>
      <%= f.text_field :text_before %> <br>

      <%= f.label :answer %>
      <%= f.text_field :answer, required: true %> <br>

      <%= f.label :after_part %>
      <%= f.text_field :text_after %> <br>

      <%= f.label :marks %>
      <%= f.number_field :marks, in: 1..10 %> <br>

      <br>
      <% f.hidden_field :_destroy %>
      <%= link_to_remove_association 'Remove', f, class: 'remove-fields btn btn-danger ml-auto' %>
    </div>
  </div>
</div>

app/views/exams/_mcq.html.erb
<p class='alert alert-secondary mt-2'> Question#<%= counter %>. <%= mcq.question %> [ <%= mcq.marks %> ] </p>
<p>1. <%= mcq.option1 %> </p>
<p>2. <%= mcq.option2 %> </p>
<p>3. <%= mcq.option3 %> </p>
<p>4. <%= mcq.option4 %> </p>

<% unless current_user.Student? %>
  <p class='alert alert-success m-2'> Option <%= mcq.correct_option %> </p>
<% end %>
<hr>

app/views/exams/_mcq_fields.html.erb
<div class='nested-fields'>
  <div class="card m-2">
    <h5 class="card-header">MCQ</h5>
    <div class="card-body">
      <%= f.label :question %>
      <%= f.text_field :question, required: true %> <br>

      <%= f.label :option_1 %>
      <%= f.text_field :option1, required: true %> <br>

      <%= f.label :option_2 %>
      <%= f.text_field :option2, required: true %> <br>

      <%= f.label :option_3 %>
      <%= f.text_field :option3, required: true %> <br>

      <%= f.label :option_4 %>
      <%= f.text_field :option4, required: true %> <br>

      <%= f.label :correct_option %>
      <%= f.select :correct_option, [1, 2, 3, 4]%> <br>

      <%= f.label :marks %>
      <%= f.number_field :marks, in: 1..10 %> <br>

      <br>
      <% f.hidden_field :_destroy %>
      <%= link_to_remove_association 'Remove', f, class: 'remove-fields btn btn-danger ml-auto' %>

    </div>
  </div>
</div>

app/views/exams/edit.html.erb
<h1> Create Exam </h1>

<% if @exam.errors.any? %>
  <% @exam.errors.full_messages.each do |error| %>
    <p class='alert alert-danger'> <%= error %> </p>
  <% end %>
<% end %>

<%= form_with model: @exam, local: true do |f| %>
  <%= f.hidden_field :teacher_id, value: current_user.id %>

  <%= f.label :subject %> <br>
  <%= f.select :subject_id, subjects_list %> <br>

  <%= f.label :title %> <br>
  <%= f.text_field :title, required: true %> <br>

  <h4> MCQs </h4>

  <% @exam&.mcqs&.each_with_index do |mcq, i| %>
    <p class='alert alert-secondary'> Question#<%= i + 1 %>. <%= mcq.question %> </p>
    <p>1. <%= mcq.option1 %> </p>
    <p>2. <%= mcq.option2 %> </p>
    <p>3. <%= mcq.option3 %> </p>
    <p>4. <%= mcq.option4 %> </p>

    <p class='alert alert-primary'> Correct: <%= mcq.correct_option %> </p>
    <%= link_to 'Remove', mcq, method: :delete, data: { confirm: 'Are you sure?' },
        class: 'btn btn-danger' %>
    <hr>
  <% end %>

  <div class='mcq-fields'>
    <%= f.fields_for :mcqs do |mcq| %>
    <% end %>
  </div>

  <h4> <%= f.label :fill_in_the_blank %> </h4>

  <% @exam&.blanks&.each_with_index do |blank, i| %>
    <p class='alert alert-secondary p-without-newline'> Question#<%= i + 1 %>. </p>
    <p class='p-without-newline m-2'> <%= blank&.text_before %> </p>
    <p class='alert alert-secondary p-without-newline m-2'> </p>
    <p class='p-without-newline m-2'> <%= blank&.text_after %> </p>

    <p class='alert alert-primary mt-4'> Correct: <%= blank.answer %> </p>
    <%= link_to 'Remove', blank, method: :delete, data: { confirm: 'Are you sure?' },
        class: 'btn btn-danger' %>

    <hr>
  <% end %>

  <div class='blank-fields'>
    <%= f.fields_for :blanks do |blank| %>
    <% end %>
  </div>

  <%= link_to_add_association 'Add Mcq', f, :mcqs, class: 'btn btn-primary mb-2', data: {
    association_insertion_node: '.mcq-fields', association_insertion_method: :append
  } %>

  <%= link_to_add_association 'Add FITB', f, :blanks, class: 'btn btn-primary mb-2', data: {
    association_insertion_node: '.blank-fields', association_insertion_method: :append
  } %>

  <br>
  <%= f.submit %>
<% end %>

app/views/exams/index.html.erb
<% if current_user.Teacher? && subjects_for_teacher %>
  <%= link_to 'Add Exam', new_exam_path, class: 'btn btn-primary m-2' %>
<% end %>

<% if @exams.blank? %>
  <p> No exams found </p>
<% else %>
<table>
  <tr>
    <th> Id </th>
    <th> Subject </th>
    <th> Title </th>
    <th> MCQs </th>
    <th> Fill in the blanks </th>
    <th> Action </th>
    <th> Action </th>
  </tr>
  <% @exams.each do |exam| %>
    <tr>
      <td> <%= exam.id %> </td>
      <td> <%= exam.subject.name %> </td>
      <td> <%= link_to "#{exam.title}", exam_path(exam) %> </td>
      <td> <%= exam.mcqs.count %> </td>
      <td> <%= exam.blanks.count %> </td>
      <td>
        <% if exam.uncertain? && current_user.Admin? %>
          <%= link_to 'Approve', exam_path(exam, exam: {status: :approved}), method: :patch, class: 'btn btn-info m-2' %>
          <%= link_to 'Reject', exam_path(exam, exam: {status: :rejected}), method: :patch, class: 'btn btn-danger m-2' %>
        <% else %>
          <p> <%= exam.status %> </p>
        <% end %>
      </td>
      <td>
        <% if current_user.Teacher? %>
          <%= link_to 'Update', edit_exam_path(exam), class: 'btn btn-secondary m-2' %>
        <% end %>
        <%= link_to 'Remove', exam_path(exam),
        data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger m-2' %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/exams/new.html.erb
<h1> Create Exam </h1>

<% if @exam.errors.any? %>
  <% @exam.errors.full_messages.each do |error| %>
    <p class='alert alert-danger'> <%= error %> </p>
  <% end %>
<% end %>

<%= form_with model: @exam, local: true do |f| %>
  <%= f.hidden_field :teacher_id, value: current_user.id %>

  <%= f.label :subject %> <br>
  <%= f.select :subject_id, subjects_list %> <br>

  <%= f.label :title %> <br>
  <%= f.text_field :title, required: true %> <br>

  <h4> MCQs </h4>

  <div class='mcq-fields'>
    <%= f.fields_for :mcqs do |mcq| %>
    <% end %>
  </div>

  <h4> <%= f.label :fill_in_the_blank %> </h4>

  <div class='blank-fields'>
    <%= f.fields_for :blanks do |blank| %>
    <% end %>
  </div>

  <%= link_to_add_association 'Add Mcq', f, :mcqs, class: 'btn btn-primary mb-2', data: {
    association_insertion_node: '.mcq-fields', association_insertion_method: :append
  } %>

  <%= link_to_add_association 'Add FITB', f, :blanks, class: 'btn btn-primary mb-2', data: {
    association_insertion_node: '.blank-fields', association_insertion_method: :append
  } %>

  <br>
  <%= f.submit %>
<% end %>

app/views/exams/show.html.erb
<% unless @exam.mcqs.blank? %>
  <h3> MCQs </h3>
<% end %>

<% @exam&.mcqs&.each_with_index do |mcq, i| %>
  <%= render 'mcq', mcq: mcq, counter: i + 1 %>
<% end %>

<% unless @exam.blanks.blank? %>
  <h3 class='mb-3'> Fill in the blanks </h3>
<% end %>

<% @exam&.blanks&.each_with_index do |blank, i| %>
  <%= render 'blank', blank: blank, counter: i + 1 %>
<% end %>