config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: 'users/invitations'
  }

  resources :users, only: %i[index destroy edit update]

  resources :admins, shallow: true do
    resources :subjects, except: :show
  end

  resources :exams
  resources :schedules, except: [:show, :edit]
  resources :results, only: [:index, :show, :create]
  resources :mcqs, only: :destroy
  resources :blanks, only: :destroy
  resources :attempts, only: :show
  resource :dashboard, only: [:show, :new]

  root 'dashboards#show'

  get '*all', to: 'dashboards#new', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_attributes, if: :devise_controller?
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :no_record

  private

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    flash[:alert] = t "#{policy_name}.#{exception.query}", scope: 'pundit', default: :default
    redirect_to root_path
  end

  def no_record
    redirect_to root_path, alert: 'Whoops, record not found'
  end

  def configure_permitted_attributes
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[type name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_alertice.html.erb
<% if alert %>
  <p class='alert alert-danger'> <%= alert %> </p>
<% elsif notice %>
  <p class='alert alert-primary'> <%= notice %> </p>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <%= link_to 'Home', root_path, class: 'btn btn-outline-primary' %>
  <% if user_signed_in? %>
    <% if current_user.Admin? %>
      <%= link_to 'Manage Users', users_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Manage Subjects', admin_subjects_path(current_user), class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Manage Exams', exams_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Manage Schedules', schedules_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Results', results_path, class: 'btn btn-primary mx-auto' %>

    <% elsif current_user.Teacher? %>
      <%= link_to 'Manage Exams', exams_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Manage Schedules', schedules_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Results', results_path, class: 'btn btn-primary mx-auto mx-auto' %>

    <% else %>
      <%= link_to 'Active exams', schedules_path, class: 'btn btn-primary mx-auto' %>
      <%= link_to 'Results', results_path, class: 'btn btn-primary mx-auto' %>
    <% end %>

    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger ml-auto' %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary ml-auto' %>
  <% end %>
</nav>